### ISSUE TITLE
Fixed x-axis labels per nested grid

### ISSUE THREAD

**Issue by michelleklsmn** [teunbrand/ggnomics#41]
Hi,

I have been using facet_nested() quite a lot recently. Thank you for creating such a useful tool! I was wondering if it was possible to create a fixed x-axis per nested grid. Currently, the plot looks like this:

![image](https://user-images.githubusercontent.com/53524546/106950134-3f1db480-672e-11eb-8afd-705a4d01c283.png)

This is the code that I used (displaying only the relevant grid parameters):
```
ggplot(KEGG_df) +  
  facet_nested(~ Enrichment + ControlDesign, nest_line = TRUE,
               scale = "free", space = "free_x") +
  geom_point(mapping = aes(x = IncubationTime, y = KEGGdescr, 
                           color = -log10(FDR), size = EnrichmentScore)) +
  theme(strip.text = element_text(size = 8))
```

The x-axis of the grid 'Down' shows all labels. In contrast, the labels '4h' and '120h - 24h' are missing from the grid 'Up' since these conditions have no upregulated KEGG pathways. The plot layout that I would like to create is:

![image](https://user-images.githubusercontent.com/53524546/106951883-a0468780-6730-11eb-8015-87bff5ac51c4.png)

I have tried using the parameter scale = "fixed" instead of scale = "free". However, this caused that all x-axis labels are displayed in each grid:

![image](https://user-images.githubusercontent.com/53524546/106954144-a9852380-6733-11eb-8293-bd62fcc22341.png)

Is there a way to fix the x-axis labels per nested grid? Meaning that the labels for both grids of 'Control: 0h' are identical and that the labels of both grids of 'Control: previous incubation time' are identical. If you require more information, please let me know. Thank you in advance!

Kind regards,
Michelle

**Comment by teunbrand** [comment]
Well there is nothing to be done from the `facet_nested()` point of view, this is just how ggplot works in `facet_grid()` too (on which the `facet_nested()` is based). 

However, I too shared your frustration, which is why I made the `facetted_pos_scales()` function that can tweak individual panel scales. Simplified example follows.

Let's make some data that should have 2 types of x-axis scales: A,B,C and D,E.
``` r
library(ggh4x)
#> Loading required package: ggplot2

df <- data.frame(
  x = c(LETTERS[1:5], LETTERS[1:5]),
  y = rnorm(10),
  outer = rep(c("Up", "Down"), each = 5),
  inner = rep(c("A", "A", "A", "B", "B"), 2)
)
```

Now, when we delete a relevant observation, we get something similar to the problem you mention: there is a C label missing from the 3rd panel x-axis.
``` r
# Delete observation C from A/Up panel
df <- df[-3,]

g <- ggplot(df, aes(x, y)) +
  geom_point() +
  facet_nested(~ outer + inner, scales = "free_x", space = "free")
print(g)
```

![](https://i.imgur.com/SgnLfj5.png)

The way I'd deal with this, is to manually set the x scale for the 3rd panel, which you can do as follows:

``` r
g + facetted_pos_scales(x = list(
  NULL, NULL, # First two panels don't need adjusting, so they're NULL
  scale_x_discrete(limits = LETTERS[1:3])
))
```

![](https://i.imgur.com/qHd07sd.png)

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

And by setting the limits for the 3rd panel manually, we've restored the C label in the 3rd panel.
Does this approach fix your problem?

**Comment by michelleklsmn** [comment]
Hi Teun,

This definitely helps me with my problem. Thank you for your help and quick reply!

Michelle
